######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 28 10:29:25 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dcm.h dialog1.h mydialog.h tcp.h widget.h
FORMS += dialog1.ui mydialog.ui widget.ui
SOURCES += dcm.cpp dialog1.cpp main.cpp mydialog.cpp tcp.cpp widget.cpp
RESOURCES += rec.qrc
